# Generated by Django 4.2.27 on 2026-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessamentoClipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('total_clipes', models.IntegerField(default=0)),
                ('clipes_processados', models.IntegerField(default=0)),
                ('clipes_sucesso', models.IntegerField(default=0)),
                ('clipes_erro', models.IntegerField(default=0)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('erro', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'processamento_clipes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
