# Generated by Django 4.2.27 on 2026-01-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processamentoclipes',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Processamento de Clipes', 'verbose_name_plural': 'Processamentos de Clipes'},
        ),
        migrations.RemoveField(
            model_name='processamentoclipes',
            name='clipes_erro',
        ),
        migrations.RemoveField(
            model_name='processamentoclipes',
            name='clipes_processados',
        ),
        migrations.RemoveField(
            model_name='processamentoclipes',
            name='clipes_sucesso',
        ),
        migrations.RemoveField(
            model_name='processamentoclipes',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='processamentoclipes',
            name='total_clipes',
        ),
        migrations.RemoveField(
            model_name='processamentoclipes',
            name='video_id',
        ),
        migrations.AddField(
            model_name='processamentoclipes',
            name='erros',
            field=models.JSONField(default=list, help_text='Lista de vídeos com erro'),
        ),
        migrations.AddField(
            model_name='processamentoclipes',
            name='resultados',
            field=models.JSONField(default=dict, help_text='Resultados do processamento por vídeo'),
        ),
        migrations.AddField(
            model_name='processamentoclipes',
            name='total_videos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processamentoclipes',
            name='videos_erro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processamentoclipes',
            name='videos_ids',
            field=models.JSONField(default=list, help_text='Lista de IDs de vídeos sendo processados'),
        ),
        migrations.AddField(
            model_name='processamentoclipes',
            name='videos_processados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processamentoclipes',
            name='videos_sucesso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='processamentoclipes',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='processamentoclipes',
            name='erro',
            field=models.TextField(blank=True, help_text='Mensagem de erro geral se houver', null=True),
        ),
        migrations.AlterField(
            model_name='processamentoclipes',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], db_index=True, default='pendente', max_length=20),
        ),
    ]
