# Generated by Django 4.2.27 on 2026-01-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r2_key', models.CharField(db_index=True, max_length=500, unique=True)),
                ('video_id', models.CharField(db_index=True, max_length=100)),
                ('channel_id', models.CharField(db_index=True, max_length=100)),
                ('youtube_video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploaded_clips',
                'ordering': ['-created_at'],
            },
        ),
    ]
