# Generated by Django 4.2.27 on 2026-01-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InProgressVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('channel_id', models.CharField(db_index=True, max_length=100)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'in_progress_videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
