# Generated by Django 4.2.27 on 2026-01-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0002_inprogressvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, help_text='ID do canal de destino', max_length=100, unique=True)),
                ('youtube_api_key', models.CharField(help_text='API Key do YouTube para buscar dados', max_length=200)),
                ('client_secret_file_path', models.CharField(help_text='Caminho do arquivo client_secret.json', max_length=500)),
                ('token_data', models.BinaryField(blank=True, help_text='Token OAuth serializado (pickle)', null=True)),
                ('token_file_path', models.CharField(blank=True, help_text='Caminho alternativo do arquivo token.pickle (se não usar token_data)', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'channel_credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inprogressvideo',
            name='source_channel_id',
            field=models.CharField(db_index=True, default=1, help_text='ID do canal fonte (de onde veio o vídeo)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inprogressvideo',
            name='target_channel_id',
            field=models.CharField(db_index=True, default=1, help_text='ID do canal de destino (onde será feito upload)', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inprogressvideo',
            name='video_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='inprogressvideo',
            unique_together={('video_id', 'target_channel_id')},
        ),
        migrations.CreateModel(
            name='ChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_channel_id', models.CharField(db_index=True, help_text='ID do canal de destino (seu canal)', max_length=100, unique=True)),
                ('source_channel_ids', models.TextField(help_text='IDs dos canais fonte separados por vírgula')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credentials', models.OneToOneField(blank=True, help_text='Credenciais de autenticação do canal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_config', to='getData.channelcredentials')),
            ],
            options={
                'db_table': 'channel_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='inprogressvideo',
            name='channel_id',
        ),
    ]
