# Generated by Django 4.2.27 on 2026-01-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0003_channelcredentials_inprogressvideo_source_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelcredentials',
            name='client_secret_r2_key',
            field=models.CharField(blank=True, help_text='Chave R2 do arquivo client_secret.json', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='channelcredentials',
            name='client_secret_file_path',
            field=models.CharField(blank=True, help_text='Caminho local do arquivo client_secret.json (deprecated, usar client_secret_r2_key)', max_length=500, null=True),
        ),
    ]
