# Generated by Django 4.2.29 on 2026-03-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0004_channelcredentials_client_secret_r2_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelconfig',
            name='upload_category_id',
            field=models.CharField(default='17', help_text='Category ID usada no upload para este canal', max_length=20),
        ),
    ]
