# Generated by Django 4.2.29 on 2026-03-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0005_channelconfig_upload_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconfig',
            name='credentials',
            field=models.ForeignKey(blank=True, help_text='Credenciais de autenticação do canal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_configs', to='getData.channelcredentials'),
        ),
    ]
