# Generated by Django 4.2.29 on 2026-03-30 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("getData", "0006_alter_channelconfig_credentials"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_from", models.CharField(db_index=True, max_length=50)),
                ("target_channel_id", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("video_id", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("r2_prefix", models.CharField(blank=True, default="", max_length=200)),
                ("status", models.CharField(choices=[("pending", "Pendente"), ("running", "Executando"), ("success", "Sucesso"), ("error", "Erro")], db_index=True, default="pending", max_length=20)),
                ("current_step", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "flow_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FlowStepRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_name", models.CharField(db_index=True, max_length=50)),
                ("status", models.CharField(choices=[("pending", "Pendente"), ("running", "Executando"), ("success", "Sucesso"), ("error", "Erro"), ("skipped", "Ignorado")], db_index=True, default="pending", max_length=20)),
                ("ok_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("flow_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="getData.flowrun")),
            ],
            options={
                "db_table": "flow_step_runs",
                "ordering": ["id"],
                "unique_together": {("flow_run", "step_name")},
            },
        ),
        migrations.CreateModel(
            name="FlowLogLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_name", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("level", models.CharField(choices=[("debug", "Debug"), ("info", "Info"), ("warning", "Aviso"), ("error", "Erro")], db_index=True, default="info", max_length=10)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("flow_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="getData.flowrun")),
            ],
            options={
                "db_table": "flow_log_lines",
                "ordering": ["id"],
            },
        ),
    ]

